dependencies:
  - base
  - hakyll
  - filepath
  - pandoc

executables:
  site:
    main: site.hs
    source-dirs:
      - src
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
